### ISSUE TITLE
지금 뭐가 안되는거?

### ISSUE THREAD

**Issue by bini59** [WareAoba/Paraglide#3]
적어두면 나도 확인해보게

커밋내역 개웃기네 ㅋㅋ

**Comment by WareAoba** [comment]
1. 일단 키 리슨까진 되는데 main.js에 이벤트 전달하고 처리하는게 안됨...
2. Sidebar.js 로그 파일에서 추출후 표시가 안됩니다

**Comment by bini59** [comment]
1번관련은 해결해서 풀리퀘 달아놓을게

**Comment by bini59** [comment]
이거 json파일 좀 줄수있음? 예제파일이 없으니 잘 모르겠네
ParaglideParaLog.json
ParaglideConfigure.json
이거 두개 있어야할듯?

**Comment by WareAoba** [comment]
제가 좀만 있다가 올리겠습니다...

**Comment by WareAoba** [comment]
[ParaglideParaLog.json](https://github.com/user-attachments/files/17791023/ParaglideParaLog.json)
[ParaglideConfigure.json](https://github.com/user-attachments/files/17791024/ParaglideConfigure.json)

경로는 제 이멜주소 있어서 살짝 수정하긴 했습니다.

**Comment by bini59** [comment]
체크했슴당
